### ISSUE TITLE
トップページの表示について

### ISSUE THREAD

**Issue by attsumi** [teroma2/nousagi#1]
## 現象

chrome で確認。
<img width="972" alt="2016-09-12 5 14 13" src="https://cloud.githubusercontent.com/assets/6082554/18429070/6a1839e0-790c-11e6-8825-d43cdc1f2cf8.png">
関連記事が表示されるべきところのスタイルが崩れている。
## どうなれば良いか
- 「コンテンツが表示されません」が表示されない
- Related entry というタイトルを表示
- それぞれに適切なスタイルがついている
## 手順
- 該当のファイルを確認
- コンテンツが表示されません、の表示がされないように修正
- 画像、タグ、日付、タイトルなどに適切なスタイルをつける

**Comment by teroma2** [comment]
@torobi まとめありがとうございます！

これっていつから起きたんですかね？
以前はこうでなかったのであれば、
WPのバージョンアップによってプラグインが動かなくなったとかな気もする。
直近の変更の影響とか。
取り急ぎざっとおもったことでした。

外出するのでまた改めてのちほどみますね！

**Comment by attsumi** [comment]
@teroma2 ありがとうございます！
正確にいつからは把握できないのですが、以前はこうではありませんでした。

直近変更したのは、記事ページですが、
トップページみた記憶ありますがこの事象でてなかったです。
また、トップページは2ヶ月くらいは触ってないです。
アップデートの可能性も考慮して調査します！

**Comment by attsumi** [comment]
<img width="372" alt="2016-09-12 7 39 34" src="https://cloud.githubusercontent.com/assets/6082554/18433098/b919f650-7920-11e6-8da3-91ab6653b18c.png">
hares.jp のバージョンを改めて確認したところ、Wordpress 4.5.4 で、最新版になっていませんでした。Wordpress 4.5.4は4月終わりリリースです。最新版は4.6.1 。

**Comment by torobi** [comment]
<img width="1087" alt="2016-09-12 8 02 09" src="https://cloud.githubusercontent.com/assets/6082554/18433763/4c6ef678-7924-11e6-9dff-c8e2507ef8e8.png">
hares.jp に関連記事を表示させるプラグイン Yet Another Related Posts Plugin が入っていて、それが古いバージョンであること、現状のバージョンでテストされていないことが確認できました。

**Comment by attsumi** [comment]
<img width="1087" alt="2016-09-12 8 02 09" src="https://cloud.githubusercontent.com/assets/6082554/18433763/4c6ef678-7924-11e6-9dff-c8e2507ef8e8.png">
hares.jp に関連記事を表示させるプラグイン Yet Another Related Posts Plugin が入っていて、そちらを停止するのを試してみたのですが、改善しませんでした。

**Comment by attsumi** [comment]
コンテンツが表示されません、は
「ピックアップ」タグ(pickupスラッグ)がついているエントリがない場合の表記。
コンテンツが表示されませんという表記はエラー文言ぽいので、「commingsoon」という表記に変えました。

**Comment by teroma2** [comment]
@torobi 
応急処置ありがとうございます！
PC版のソースみたんですが、
どっかのdivに入るべきコンテンツが、ただしく出力されてないか、divの閉じタグが足りないかなどが考えられます。

確かリリース前の開発段階ではこの崩れてるエリア、グレーのゾーンに横並びに4記事表示されてたような…？すみません、思い出せないです。

なので、まず開発環境で以前どうだったかを見た方がいいで。→hares.devの状態をみてただしい状態を確認したほうがいいですね。

最近わたしソースみてないんでどんな構造だったか覚えてない…

**Comment by teroma2** [comment]
プラグインが原因でした！

リリース後の不具合は、リリース後に追加されたプラグインを疑おう！という教訓でした。

**Comment by attsumi** [comment]
調査ありがとうございました！教訓になりました。解決したということでcloseします。
